name: dashboard_secureeyes

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.5
  mqtt_client: ^10.3.0
  syncfusion_flutter_gauges: ^26.2.10
  flutter_sound_record: ^3.3.2
  flutter_sound: ^9.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
